# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [22]:
import numpy as np
print(np.zeros((2, 3)))
print(np.empty((2,3)))
# np.zeroes 內的元素值為0，np.empty內的元素為隨機的數

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [23]:
# 記得先 Import 正確的套件
import numpy as np
import numpy.random 

In [26]:
# 參考解答

a = np.random.rand(2, 3)
print(a)
print(np.around(a))

[[0.62398637 0.42051293 0.92677651]
 [0.96145169 0.83856132 0.02997429]]
[[1. 0. 1.]
 [1. 1. 0.]]


'\nYour Code\n'

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [31]:
m = 20
n = 40

print(np.around(np.random.rand(2,3)*(n-m)+m))

[[25. 23. 23.]
 [31. 30. 35.]]
