# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [2]:
import numpy as np
a = np.arange(10)
print('a.sum:',a.sum())
print('np.sum(a):',np.sum(a))
print('sum(a):',sum(a))


# 功能上沒有差別，只是使用函式層級不同

a.sum: 45
np.sum(a): 45
sum(a): 45


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [6]:
# 記得先 Import 正確的套件

import numpy as np
A = np.random.random((5, 5))
normalize_A = A/np.linalg.norm(A)
print('original:',A)
print('normalize:',normalize_A)

original: [[0.52495501 0.38753247 0.81595708 0.08459972 0.04264754]
 [0.95390002 0.39103231 0.9864342  0.01897372 0.43132394]
 [0.05958815 0.03649712 0.22984158 0.01098135 0.08929177]
 [0.65347327 0.87031839 0.24175341 0.61427405 0.9824052 ]
 [0.66590634 0.30700393 0.59908212 0.31438505 0.6609438 ]]
normalize: [[0.1928958  0.1423996  0.29982511 0.03108634 0.01567093]
 [0.35051253 0.14368563 0.36246728 0.00697193 0.15849087]
 [0.02189579 0.01341094 0.08445576 0.00403512 0.03281044]
 [0.2401201  0.31980029 0.08883279 0.22571627 0.36098682]
 [0.24468866 0.11280923 0.22013396 0.11552143 0.24286516]]


In [ ]:
A = np.random.random((5, 5))

'''
Your Code
'''

array([[0.13197583, 0.1034873 , 0.        , 0.31390653, 0.35846645],
       [0.14777047, 0.28417508, 0.75999011, 0.29030305, 0.72055306],
       [0.98492508, 0.41249799, 1.        , 0.39756699, 0.39109584],
       [0.85537752, 0.84696945, 0.69635415, 0.86720675, 0.61212718],
       [0.24295928, 0.99120832, 0.09074347, 0.78251208, 0.57787873]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [ ]:
A = np.random.random(10)

[ 0.29347583  0.59303277 -1.          0.38043546  0.63265939  0.32472618
  0.11340241  0.68136955  0.89905432  0.74769935]


In [22]:
A = np.random.random(10)
print(A)

A[A==A.max()]=-1
print(A)

[0.77696093 0.00248985 0.5682485  0.08110925 0.98495289 0.31541805
 0.01641914 0.436445   0.61231864 0.64893115]
[ 0.77696093  0.00248985  0.5682485   0.08110925 -1.          0.31541805
  0.01641914  0.436445    0.61231864  0.64893115]


In [23]:
# find array index of maximum
print(np.amax(A))
print(np.where(A==np.amax(A)))

0.7769609259384227
(array([0]),)
