# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [2]:
import numpy as np
a = np.arange(10)
print('a.sum:',a.sum())
print('np.sum(a):',np.sum(a))
print('sum(a):',sum(a))


# sum()是python內建的函數，所有型態都可用。
# ndarray.sum()和np.sum()，是陣列專有的函式，差別在定義在np或是array下

a.sum: 45
np.sum(a): 45
sum(a): 45


### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [7]:
# 記得先 Import 正確的套件

import numpy as np
A = np.random.random((5, 5))

normalize_A1 = (A - A.min()) / (A.max() - A.min())
print('original:\n',A)
print('normalize_A1:\n',normalize_A1)

original:
 [[0.50544013 0.94757717 0.38325589 0.63057123 0.95601419]
 [0.35023065 0.09814836 0.99434666 0.30184611 0.7821398 ]
 [0.46283221 0.97515423 0.02514511 0.93807013 0.32454957]
 [0.26899203 0.56131352 0.99925819 0.78816375 0.64816173]
 [0.72030587 0.13478686 0.05675324 0.75352114 0.2072315 ]]
normalize_A1:
 [[0.49305879 0.94694556 0.36762752 0.62151523 0.95560679]
 [0.33372464 0.0749433  0.99495794 0.28405429 0.77711172]
 [0.44931857 0.97525547 0.         0.93718588 0.30736109]
 [0.25032712 0.55041701 1.         0.78329575 0.6395732 ]
 [0.71363456 0.11255547 0.03244812 0.74773252 0.18692531]]


In [ ]:
A = np.random.random((5, 5))

'''
Your Code
'''

array([[0.13197583, 0.1034873 , 0.        , 0.31390653, 0.35846645],
       [0.14777047, 0.28417508, 0.75999011, 0.29030305, 0.72055306],
       [0.98492508, 0.41249799, 1.        , 0.39756699, 0.39109584],
       [0.85537752, 0.84696945, 0.69635415, 0.86720675, 0.61212718],
       [0.24295928, 0.99120832, 0.09074347, 0.78251208, 0.57787873]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [ ]:
A = np.random.random(10)

[ 0.29347583  0.59303277 -1.          0.38043546  0.63265939  0.32472618
  0.11340241  0.68136955  0.89905432  0.74769935]


In [22]:
A = np.random.random(10)
print(A)

A[A==A.max()]=-1
print(A)

[0.77696093 0.00248985 0.5682485  0.08110925 0.98495289 0.31541805
 0.01641914 0.436445   0.61231864 0.64893115]
[ 0.77696093  0.00248985  0.5682485   0.08110925 -1.          0.31541805
  0.01641914  0.436445    0.61231864  0.64893115]


In [23]:
# find array index of maximum
print(np.amax(A))
print(np.where(A==np.amax(A)))

0.7769609259384227
(array([0]),)
